version: '3.8'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5679:5678"
    volumes:
      - data:/home/node/.n8n
      - data_venv:/data # 虚拟环境将保存在这里
    environment:
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    user: root
    entrypoint: ["tini", "--"]
    command: >
      /bin/sh -c "
      apk add --no-cache py3-virtualenv && \
      python3 -m venv /data/venv && \
      chown -R node:node /data/venv && \
      chmod +x /docker-entrypoint.sh && \
      exec su -l node -c '/docker-entrypoint.sh \"$@\"'
      "
    networks:
      - default

volumes:
  data:
  data_venv: # 为虚拟环境定义 volume

networks:
  default:
    external: true
    name: n8n