services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5679:5678"
    volumes:
      - data:/home/node/.n8n
      - data_venv:/data # 虚拟环境将保存在这里
    environment:
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
    user: root
    # 2. 覆盖默认入口点，执行一个内联脚本
    entrypoint: |
      sh -c '
        set -e
        echo "Starting custom initialization..."

        # 安装依赖 (如果尚未安装)
        if ! apk -e info py3-virtualenv > /dev/null 2>&1; then
          echo "Installing py3-virtualenv..."
          apk add --no-cache py3-virtualenv
        fi

        # 创建虚拟环境 (如果尚不存在)
        if [ ! -d "/data/venv/bin" ]; then
          echo "Creating Python virtual environment in /data/venv..."
          python3 -m venv /data/venv
        fi

        # 确保权限正确
        echo "Setting permissions for /data/venv..."
        chown -R node:node /data/venv

        # 3. 切换到 "node" 用户并执行原始的 entrypoint
        exec su -s /bin/sh -c "exec /docker-entrypoint.sh" node
      '
    networks:
      - default

volumes:
  data:
  data_venv: # 为虚拟环境定义 volume

networks:
  default:
    external: true
    name: n8n
